<template>
  <v-container class="mt-8 max-width-1000 d-flex flex-column" style="height: calc(100vh - 120px);">
    
    <div class="mb-6">
      <h1 class="text-h3 font-weight-bold mb-2">Dev Assistant <span class="text-gradient">Chatbot</span></h1>
      <p class="text-h6 text-medium-emphasis">Ask any technical questions based on internal knowledge and documents.</p>
    </div>

    <!-- Chat Window -->
    <v-card class="glass-card flex-grow-1 d-flex flex-column overflow-hidden mb-6" elevation="0">
      
      <!-- Messages Area -->
      <v-card-text class="flex-grow-1 overflow-y-auto pa-4 pa-sm-6" ref="messagesContainer">
        
        <div v-if="messages.length === 0" class="h-100 d-flex flex-column align-center justify-center opacity-50">
          <v-icon size="64" class="mb-4">mdi-robot-outline</v-icon>
          <h3 class="text-h5">How can I help you today?</h3>
          <p>Try asking about our system architecture, APIs, or common errors.</p>
        </div>

        <div v-for="(msg, index) in messages" :key="index" class="mb-4">
          
          <!-- User Message -->
          <div v-if="msg.role === 'user'" class="d-flex justify-end mb-4">
            <v-card class="bg-primary px-4 py-3 rounded-lg text-white max-w-75" elevation="2">
              {{ msg.content }}
            </v-card>
          </div>

          <!-- Assistant Message -->
          <div v-if="msg.role === 'assistant'" class="d-flex justify-start mb-4">
            <v-card class="bg-surface-light px-4 py-3 rounded-lg max-w-85" elevation="1">
              <div v-html="formatMessage(msg.content)" class="markdown-body"></div>
              
              <!-- Sources -->
              <div v-if="msg.sources && msg.sources.length > 0" class="mt-4 pt-4 border-t opacity-80">
                <div class="text-caption font-weight-bold mb-2">Sources:</div>
                <div class="d-flex flex-wrap gap-2">
                  <v-chip
                    v-for="(source, i) in msg.sources"
                    :key="i"
                    size="small"
                    variant="outlined"
                    color="primary"
                    :href="source.link.startsWith('/') ? null : source.link"
                    :to="source.link.startsWith('/') ? source.link : null"
                    target="_blank"
                    class="mr-2 mb-2 custom-chip"
                  >
                    <v-icon start size="x-small">{{ source.type === 'Database' ? 'mdi-database' : 'mdi-file-document' }}</v-icon>
                    {{ source.type }}
                  </v-chip>
                </div>
              </div>
            </v-card>
          </div>

        </div>

        <!-- Loading Indicator -->
        <div v-if="isLoading" class="d-flex justify-start mb-4">
          <v-card class="bg-surface-light px-4 py-3 rounded-lg" elevation="1">
            <div class="d-flex align-center">
              <v-progress-circular indeterminate color="primary" size="20" class="mr-3"></v-progress-circular>
              <span class="text-medium-emphasis">Thinking...</span>
            </div>
          </v-card>
        </div>

      </v-card-text>

      <!-- Input Area -->
      <v-divider></v-divider>
      <div class="bg-surface-darken-1">
        <v-card-actions class="pa-4 pb-2">
          <v-text-field
            v-model="inputQuery"
            placeholder="Type your question..."
            variant="solo-filled"
            bg-color="transparent"
            hide-details
            flat
            @keyup.enter="sendMessage"
            :disabled="isLoading"
            rounded="pill"
          >
            <template v-slot:append-inner>
              <v-btn
                icon="mdi-send"
                color="primary"
                variant="flat"
                size="small"
                class="ml-2 bg-gradient-primary"
                @click="sendMessage"
                :loading="isLoading"
                :disabled="!inputQuery.trim() || isLoading"
              ></v-btn>
            </template>
          </v-text-field>
        </v-card-actions>
        <div class="text-center text-caption text-medium-emphasis pb-3">
          Answer generated by AI may be inaccurate.
        </div>
      </div>
      
    </v-card>

  </v-container>
</template>

<script setup>
import { ref, nextTick } from 'vue'
import api from '../services/api'
import { marked } from 'marked'

const inputQuery = ref('')
const messages = ref([])
const isLoading = ref(false)
const messagesContainer = ref(null)

const scrollToBottom = () => {
  nextTick(() => {
    if (messagesContainer.value) {
      const el = messagesContainer.value.$el || messagesContainer.value;
      el.scrollTop = el.scrollHeight;
    }
  })
}

const formatMessage = (text) => {
  if (!text) return ''
  return marked(text)
}

const sendMessage = async () => {
  const queryText = inputQuery.value.trim()
  if (!queryText || isLoading.value) return

  // Add user message
  messages.value.push({
    role: 'user',
    content: queryText
  })
  
  inputQuery.value = ''
  isLoading.value = true
  scrollToBottom()

  try {
    const historyPayload = messages.value
      .slice(0, -1)
      .filter(m => !m.content.includes("⚠️ **Error:**"))
      .slice(-40)
      .map(m => ({ role: m.role, content: m.content }))

    const response = await api.post('/api/chat/query', { 
      query: queryText,
      history: historyPayload
    })
    const data = response.data
    
    messages.value.push({
      role: 'assistant',
      content: data.answer || "I'm sorry, I couldn't generate an answer.",
      sources: data.sources || []
    })
  } catch (error) {
    console.error('Chat error:', error)
    messages.value.push({
      role: 'assistant',
      content: "⚠️ **Error:** Failed to connect to the backend or the AI service. Please try again later."
    })
  } finally {
    isLoading.value = false
    scrollToBottom()
  }
}
</script>

<style scoped>
.max-width-1000 {
  max-width: 1000px;
  margin: 0 auto;
}
.max-w-75 {
  max-width: 75%;
}
.max-w-85 {
  max-width: 85%;
}
.border-t {
  border-top: 1px solid rgba(128, 128, 128, 0.2);
}
.markdown-body :deep(p) { margin-bottom: 12px; }
.markdown-body :deep(p:last-child) { margin-bottom: 0; }
.markdown-body :deep(pre) {
  background: rgba(0,0,0,0.1);
  padding: 12px;
  border-radius: 8px;
  overflow-x: auto;
  margin-bottom: 12px;
}
.markdown-body :deep(code) {
  font-family: monospace;
  background: rgba(0,0,0,0.1);
  padding: 2px 4px;
  border-radius: 4px;
}
.custom-chip:hover {
  background-color: rgba(var(--v-theme-primary), 0.1);
}
</style>
